language: node_js
before_script:
    - sh -e /etc/init.d/xvfb start
    - curl -sq https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.17.tar.gz -o sdk.tar.gz
    - tar zxvf sdk.tar.gz
    - cd addon-sdk*
    - . bin/activate
    - cd ..
env:
    - DISPLAY=':99.0'
script: cfx test --verbose
