language: node_js
node_js:
    - "6.1"
sudo: false
addons:
    apt:
        packages:
            - aria2
env:
    global:
        - DISPLAY=':99.0'
        - FIREFOX_BINARY='./firefox/firefox'
    matrix:
        - FIREFOX_RELEASE='nightly-latest'
        - FIREFOX_RELEASE='aurora-latest'
        - FIREFOX_RELEASE='beta-linux64-add-on-devel'
        - FIREFOX_RELEASE='release-linux64-add-on-devel'
        - FIREFOX_RELEASE='43.0'
        - FIREFOX_RELEASE='esr-latest'
matrix:
    fast_finish: true
    allow_failures:
        #- env: FIREFOX_RELEASE='latest'
        #- env: FIREFOX_RELEASE='beta-latest'
        #- env: FIREFOX_RELEASE='esr-latest'
cache:
    directories:
        - node_modules
before_script:
    - npm install
    - test $FIREFOX_RELEASE != nightly-latest               || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != aurora-latest                || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != beta-linux64-add-on-devel    || bash -x scripts/fetch-unbranded.sh $FIREFOX_RELEASE
    - test $FIREFOX_RELEASE != release-linux64-add-on-devel || bash -x scripts/fetch-unbranded.sh $FIREFOX_RELEASE
    - test $FIREFOX_RELEASE != '43.0'                       || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != esr-latest                   || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - tar xvf firefox-$FIREFOX_RELEASE.tar.bz2
    - sh -e /etc/init.d/xvfb start
script:
    - npm run build
    - npm test
    - npm run lint
