language: node_js
node_js:
    - "5.9"
sudo: false
addons:
    apt:
        packages:
            - aria2
env:
    global:
        - DISPLAY=':99.0'
        - FIREFOX_BIN='./firefox/firefox'
    matrix:
        - FIREFOX_RELEASE='nightly-latest'
        - FIREFOX_RELEASE='aurora-latest'
        - FIREFOX_RELEASE='latest'
        - FIREFOX_RELEASE='43.0'
        - FIREFOX_RELEASE='esr-latest'
        #- FIREFOX_RELEASE='nightly'
matrix:
    fast_finish: true
    allow_failures:
        #- env: FIREFOX_RELEASE='latest'
        #- env: FIREFOX_RELEASE='beta-latest'
        #- env: FIREFOX_RELEASE='esr-latest'
cache:
    directories:
        - node_modules
before_script:
    - npm install
    - npm install grunt -g
    - npm install grunt-cli -g
    - test $FIREFOX_RELEASE = nightly || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://download.mozilla.org/?product=firefox-$FIREFOX_RELEASE&os=linux64&lang=en-US"
    - test $FIREFOX_RELEASE != nightly || aria2c -o firefox-$FIREFOX_RELEASE.tar.bz2 "https://archive.mozilla.org`curl -s https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/ | grep -E '/pub/firefox/nightly/latest-mozilla-central/firefox-[^\"]+.linux-x86_64.tar.bz2' -o | sort | tail -1`"
    - tar xvf firefox-$FIREFOX_RELEASE.tar.bz2
    - sh -e /etc/init.d/xvfb start
script:
    #- npm run jpm_test
    - bash test/run_tests_with_travisci_workaround.sh
    - npm run -s eslint
