language: node_js
before_script:
    - sudo $(which npm) install -g grunt
    - sudo $(which npm) install -g grunt-cli
    - sudo $(which npm) install grunt-run
    - sudo $(which npm) install grunt-contrib-jshint
    - curl -sq https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.17.tar.gz -o sdk.tar.gz
    - tar zxf sdk.tar.gz
    - cd addon-sdk*
    - . bin/activate
    - cd ..
    - sh -e /etc/init.d/xvfb start
env:
    - DISPLAY=':99.0'
script: grunt travis --verbose
